name: Loki Meyburg
description: "This is where I write about UI design and product management"
meta_description: "Building great things"

markdown: redcarpet
pygments: true
logo: false
paginate: 15

baseurl: '/'

# Details for the RSS feed generator
url:            'http://www.lokimeyburg.com'
author:         'Loki Meyburg'
