name: Loki Meyburg
description: "This is where I write about tech, mobile & startups."
meta_description: "Building great things"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
excerpt_separator: <!--more-->
baseurl: '/'

# Details for the RSS feed generator
url:            'http://www.lokimeyburg.com'
author:         'Loki Meyburg'

gems: ['jekyll-paginate']

collections:
  projects:
    output: true
    permalink: /projects/:path/